version: '3'
services:
  mf-sm:
    build:
      context: ./state-management
      dockerfile: dockerfile
    container_name: c_sm

  mf-cart:
    build:
      context: ./cart
      dockerfile: dockerfile
      args:
        - gateway_base_url=$gateway_url
    container_name: c_cart
    depends_on:
      - mf-sm

  mf-prod:
    build:
      context: ./products
      dockerfile: dockerfile
      args:
        - gateway_base_url=$gateway_url
    container_name: c_prod
    depends_on:
      - mf-sm

  mf-api-gateway:
    build:
      context: ./api-gateway
      dockerfile: dockerfile
    ports:
      - 9090:9090
    container_name: c_api_gateway
    environment:
      #notice below environment names are set to above three containers name, so internally api gateway, can connect to micro frontend modules
      - state_management_container_name=http://c_sm/
      - cart_container_name=http://c_cart/
      - products_container_name=http://c_prod/

  mf-host:
    build:
      context: ./host
      dockerfile: dockerfile
      args:
        - gateway_base_url=$gateway_url
    ports:
      - 8080:80
    container_name: c_host
    depends_on:
      - mf-sm
      - mf-cart
      - mf-prod
      - mf-api-gateway
