FROM node:lts-alpine as stage
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:mainline-alpine3.18-slim
COPY --from=stage ./app/dist/ /usr/share/nginx/html/
EXPOSE 80