FROM node:18.18-alpine as stage
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
ARG gateway_base_url=
RUN npm run build

FROM nginx:mainline-alpine3.18-slim
COPY --from=stage ./app/dist/ /usr/share/nginx/html/
EXPOSE 80